name: 'BrowserStack Test'

on: [push, pull_request]

jobs:
  ubuntu-job:
    name: 'BrowserStack Test on Ubuntu'
    runs-on: ubuntu-latest  # Can be self-hosted runner also

    steps:
    
      - name: 'BrowserStack Env Setup'  # Invokes the setup-env action
        uses: browserstack/github-actions/setup-env@master
        with:
          username:  ${{ secrets.BROWSERSTACK_USERNAME }}
          access-key: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}


# Perform tests
      - name: 'Checkout the repository'
        uses: actions/checkout@v2
        
      - name: 'Runing tests with maven in Browserstack'
        run: mvn test -Dviewmode="web_chrome"
        
        
